version: '2.0'

services:

  lorawan-bacnet-bridge:
    
    image: rakwireless/lorawan-bacnet-bridge
    container_name: lorawan-bacnet-bridge
    restart: unless-stopped
    network_mode: host
    
    # Uncomment the following lines to build the docker image locally by using `docker compose build`
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    
    # Mount the configuration folder to persist changes accross container reboots
    volumes:
      - ./config:/app/config

    # You can either configure the service using a config.yml file inside the configuration folder
    # or use environment variables here (check the README)
    #environment:
    #  - MQTT_SERVER=eu1.cloud.thethings.network
    #  - MQTT_PORT=1883
    #  - MQTT_USERNAME=my-app@ttn
    #  - MQTT_PASSWORD=NNSXS.UTGKWB.........UPQ
    #  - BACNET_IP=192.168.1.162
